#!/bin/bash

CURR_DIR=$(pwd)
MARSHAL_CONFIG_DIR=/scratch/edwinlim/hyperscale-soc-chipyard/ccbench-new/software/marshal-configs
FIREMARSHAL_DIR=/scratch/edwinlim/hyperscale-soc-chipyard/software/firemarshal
WORKLOAD_DIR=/scratch/edwinlim/hyperscale-soc-chipyard/sims/firesim/deploy/workloads

cd $FIREMARSHAL_DIR

./marshal clean ${MARSHAL_CONFIG_DIR}/caches-baremetal.yaml
./marshal build ${MARSHAL_CONFIG_DIR}/caches-baremetal.yaml
./marshal install ${MARSHAL_CONFIG_DIR}/caches-baremetal.yaml

sed -i 's/"uartlog"/"uartlog", "metasim_stderr.out", "metasim_waveform.vpd"/g' ${WORKLOAD_DIR}/caches-baremetal.json
cd $CURR_DIR
