#!/usr/bin/bash

# Builds and installs a given workload in /ccbench-new/software/marshal-configs
#
# Arguments
#     arg1: workload name
#
# Example Usage
#     ./gen_workload caches-br.json
HOME_DIR=/home/centos/firesim
WORK_DIR=${HOME_DIR}/deploy/workloads/ccbench-new
MARSHAL_CONFIG_DIR=${WORK_DIR}/software/marshal-configs
CURR_DIR=$(pwd)

cd $HOME_DIR
source sourceme-f1-manager.sh

cd /home/centos/firesim/target-design/chipyard/software/firemarshal
./marshal build ${MARSHAL_CONFIG_DIR}/${1}
./marshal install ${MARSHAL_CONFIG_DIR}/${1}

cd $CURR_DIR
