#!/usr/bin/bash

# Parses run results from strided-br workload and outputs FASED performance results
# 
# Arguments
#     arg1: NO_LLC_RESULT_DIR
#     arg2: 4MBLLC_8WAY_RESULT_DIR
#     arg3: 4MBLLC_4WAY_RESULT_DIR
#     arg4: 4MBLLC_2WAY_RESULT_DIR
#     arg5: 4MBLLC_DMAP_RESULT_DIR
#     arg6: 32MBLLC_DMAP_RESULT_DIR
#     arg7: absolute path of where to store result plot
#
# Example Usage
#

# Testing values while sim is running
_NO_LLC_RESULT_DIR=/home/centos/firesim/deploy/results-workload/2022-08-31--18-44-35-strided-br
_4MBLLC_8WAY_RESULT_DIR=/home/centos/firesim/deploy/results-workload/2022-08-31--19-27-18-strided-br
_4MBLLC_4WAY_RESULT_DIR=/home/centos/firesim/deploy/results-workload/2022-08-31--20-03-18-strided-br
_4MBLLC_2WAY_RESULT_DIR=/home/centos/firesim/deploy/results-workload/2022-08-31--20-40-18-strided-br
#4MBLLC_DMAP_RESULT_DIR=/home/centos/firesim/deploy/results-workload/2022-08-31--21-17-15-strided-br
#32MBLLC_DMAP_RESULT_DIR=/home/centos/firesim/deploy/results-workload/
PLOT_PATH=/home/centos/firesim/deploy/workloads/ccbench-new/plots/testplot.pdf
#RESULT_CSV_PATHS=(
#    "strided-br-stride-1/stride-1.csv"
#    "strided-br-stride-4/stride-4.csv"
#    "strided-br-stride-16/stride-16.csv"
#    "strided-br-stride-64/stride-64.csv"
#    "strided-br-stride-256/stride-256.csv"
#)

python3 parse-strided-csv.py ${_NO_LLC_RESULT_DIR}/strided-br-stride-1/stride-1.csv \
                             ${_NO_LLC_RESULT_DIR}/strided-br-stride-4/stride-4.csv \
                             ${_NO_LLC_RESULT_DIR}/strided-br-stride-16/stride-16.csv \
                             ${_NO_LLC_RESULT_DIR}/strided-br-stride-64/stride-64.csv \
                             ${_NO_LLC_RESULT_DIR}/strided-br-stride-256/stride-256.csv \
                             /home/centos/firesim/deploy/workloads/ccbench-new/plots/_NO_LLC.pdf

python3 parse-strided-csv.py ${_4MBLLC_8WAY_RESULT_DIR}/strided-br-stride-1/stride-1.csv \
                             ${_4MBLLC_8WAY_RESULT_DIR}/strided-br-stride-4/stride-4.csv \
                             ${_4MBLLC_8WAY_RESULT_DIR}/strided-br-stride-16/stride-16.csv \
                             ${_4MBLLC_8WAY_RESULT_DIR}/strided-br-stride-64/stride-64.csv \
                             ${_4MBLLC_8WAY_RESULT_DIR}/strided-br-stride-256/stride-256.csv \
                             /home/centos/firesim/deploy/workloads/ccbench-new/plots/_4MBLLC_8WAY.pdf

python3 parse-strided-csv.py ${_4MBLLC_4WAY_RESULT_DIR}/strided-br-stride-1/stride-1.csv \
                             ${_4MBLLC_4WAY_RESULT_DIR}/strided-br-stride-4/stride-4.csv \
                             ${_4MBLLC_4WAY_RESULT_DIR}/strided-br-stride-16/stride-16.csv \
                             ${_4MBLLC_4WAY_RESULT_DIR}/strided-br-stride-64/stride-64.csv \
                             ${_4MBLLC_4WAY_RESULT_DIR}/strided-br-stride-256/stride-256.csv \
                             /home/centos/firesim/deploy/workloads/ccbench-new/plots/_4MBLLC_4WAY.pdf

python3 parse-strided-csv.py ${_4MBLLC_2WAY_RESULT_DIR}/strided-br-stride-1/stride-1.csv \
                             ${_4MBLLC_2WAY_RESULT_DIR}/strided-br-stride-4/stride-4.csv \
                             ${_4MBLLC_2WAY_RESULT_DIR}/strided-br-stride-16/stride-16.csv \
                             ${_4MBLLC_2WAY_RESULT_DIR}/strided-br-stride-64/stride-64.csv \
                             ${_4MBLLC_2WAY_RESULT_DIR}/strided-br-stride-256/stride-256.csv \
                             /home/centos/firesim/deploy/workloads/ccbench-new/plots/_4MBLLC_2WAY.pdf

