#!/usr/bin/bash

# Runs a given workload on multiple different LLC cache configurations to obtain 
# FASED performance results
#
# Arguments
#     arg1: workload name
#     arg2: job name
#
# Example Usage
#     ./run-cache-sweep caches-br caches
HOME_DIR=/home/centos/firesim
RESULT_DIR=${HOME_DIR}/deploy/results-workload
WORK_DIR=${HOME_DIR}/deploy/workloads/ccbench-new
COPY_DIR=${WORK_DIR}/results
JOB_NAME=${1}-${2}
LLC_settings=(
    "mm_llc_wayBits_0"
    "mm_llc_setBits_0"
    "mm_llc_blockBits_0"
    "mm_llc_activeMSHRs_0"
    "mm_llc_wayBits_1"
    "mm_llc_setBits_1"
    "mm_llc_blockBits_1"
    "mm_llc_activeMSHRs_1"
    "mm_llc_wayBits_2"
    "mm_llc_setBits_2"
    "mm_llc_blockBits_2"
    "mm_llc_activeMSHRs_2"
    "mm_llc_wayBits_3"
    "mm_llc_setBits_3"
    "mm_llc_blockBits_3"
    "mm_llc_activeMSHRs_3"
)
direct_mapped=(0 15 7 8 0 15 7 8 0 15 7 8 0 15 7 8)
two_way_set=(1 14 7 8 1 14 7 8 1 14 7 8 1 14 7 8)
four_way_set=(2 13 7 8 2 13 7 8 2 13 7 8 2 13 7 8)
eight_way_set=(3 12 7 8 3 12 7 8 3 12 7 8 3 12 7 8)


cd $WORK_DIR

# Clear copy directory if it is not empty
if [ ! -z "$(ls -A $COPY_DIR)" ]; then
    rm -r ${COPY_DIR}/*
fi

# Initialize separate directories for each different configuration
mkdir ${COPY_DIR}/8-way-set-associative
mkdir ${COPY_DIR}/4-way-set-associative
mkdir ${COPY_DIR}/2-way-set-associative
mkdir ${COPY_DIR}/direct-mapped


# Run sweep with default config
firesim kill

for i in ${!LLC_settings[@]}; do
    python3 change-conf.py fased_sweep_protomegaboom.conf ${LLC_settings[$i]} ${eight_way_set[$i]}
done
firesim infrasetup
firesim runworkload

RESULT_NAME=$(ls $RESULT_DIR -t | head -1)
cp ${RESULT_DIR}/${RESULT_NAME}/${JOB_NAME}/run_result.csv ${COPY_DIR}/8-way-set-associative/run_result.csv
cp ${RESULT_DIR}/${RESULT_NAME}/${JOB_NAME}/uartlog ${COPY_DIR}/8-way-set-associative/uartlog


# Run sweep with 4-way config
firesim kill

for i in ${!LLC_settings[@]}; do
    python3 change-conf.py fased_sweep_protomegaboom.conf ${LLC_settings[$i]} ${four_way_set[$i]}
done
firesim infrasetup
firesim runworkload

RESULT_NAME=$(ls $RESULT_DIR -t | head -1)
cp ${RESULT_DIR}/${RESULT_NAME}/${JOB_NAME}/run_result.csv ${COPY_DIR}/4-way-set-associative/run_result.csv
cp ${RESULT_DIR}/${RESULT_NAME}/${JOB_NAME}/uartlog ${COPY_DIR}/4-way-set-associative/uartlog


# Run sweep with 2-way set associative
firesim kill

for i in ${!LLC_settings[@]}; do
    python3 change-conf.py fased_sweep_protomegaboom.conf ${LLC_settings[$i]} ${two_way_set[$i]}
done
firesim infrasetup
firesim runworkload

RESULT_NAME=$(ls $RESULT_DIR -t | head -1)
cp ${RESULT_DIR}/${RESULT_NAME}/${JOB_NAME}/run_result.csv ${COPY_DIR}/2-way-set-associative/run_result.csv
cp ${RESULT_DIR}/${RESULT_NAME}/${JOB_NAME}/uartlog ${COPY_DIR}/2-way-set-associative/uartlog


# Run sweep with direct mapped
firesim kill

for i in ${!LLC_settings[@]}; do
    python3 change-conf.py fased_sweep_protomegaboom.conf ${LLC_settings[$i]} ${direct_mapped[$i]}
done
firesim infrasetup
firesim runworkload

RESULT_NAME=$(ls $RESULT_DIR -t | head -1)
cp ${RESULT_DIR}/${RESULT_NAME}/${JOB_NAME}/run_result.csv ${COPY_DIR}/direct-mapped/run_result.csv
cp ${RESULT_DIR}/${RESULT_NAME}/${JOB_NAME}/uartlog ${COPY_DIR}/direct-mapped/uartlog
