#!/usr/bin/bash

# Runs the caches-br workload on multiple different LLC cache configurations to obtain
# FASED performance results

LLC_settings=(
    "mm_llc_wayBits_0"
    "mm_llc_setBits_0"
    "mm_llc_blockBits_0"
    "mm_llc_activeMSHRs_0"
    "mm_llc_wayBits_1"
    "mm_llc_setBits_1"
    "mm_llc_blockBits_1"
    "mm_llc_activeMSHRs_1"
    "mm_llc_wayBits_2"
    "mm_llc_setBits_2"
    "mm_llc_blockBits_2"
    "mm_llc_activeMSHRs_2"
    "mm_llc_wayBits_3"
    "mm_llc_setBits_3"
    "mm_llc_blockBits_3"
    "mm_llc_activeMSHRs_3"
)
MiB4_8_way_set=(3 10 7 8 3 10 7 8 3 10 7 8 3 10 7 8)
MiB4_4_way_set=(2 11 7 8 2 11 7 8 2 11 7 8 2 11 7 8)
MiB4_2_way_set=(1 12 7 8 1 12 7 8 1 12 7 8 1 12 7 8)
MiB4_direct_mapped=(0 13 7 8 0 13 7 8 0 13 7 8 0 13 7 8)
MiB32_direct_mapped=(0 16 7 8 0 16 7 8 0 16 7 8 0 16 7 8)

FIRESIM_DIR=/home/centos/firesim
RESULT_DIR=/home/centos/firesim/deploy/results-workload
WORK_DIR=/home/centos/firesim/deploy/workloads/ccbench-new
COPY_DIR=/home/centos/firesim/deploy/workloads/ccbench-new/results
CHANGE_CONF_PY=/home/centos/firesim/deploy/workloads/ccbench-new/software/scripts/change-conf.py
FIRESIM_CONFIGS=/home/centos/firesim/deploy/workloads/ccbench-new/software/firesim-configs


# Configuring config_runtime.ini for the no-LLC sim
cp ${FIRESIM_CONFIGS}/FASED_no_LLC_caches-br_sweep_runtime.ini ${FIRESIM_DIR}/deploy/config_runtime.ini
firesim launchrunfarm

# Run sweep with no-LLC configuration
firesim infrasetup
firesim runworkload
RESULT_NAME=$(ls $RESULT_DIR -t | head -1)
NO_LLC_RESULT_DIR=${RESULT_DIR}/${RESULT_NAME}
firesim terminaterunfarm --forceterminate


# Configuring config_runtime.ini for the LLC sim
cp ${FIRESIM_CONFIGS}/FASED_LLC_caches-br_sweep_runtime.ini ${FIRESIM_DIR}/deploy/config_runtime.ini
firesim launchrunfarm

# Run sweep w/ 4 MiB 8-way LLC
for i in ${!LLC_settings[@]}; do
    python3 $CHANGE_CONF_PY fased-sweep-protomegaboom.conf ${LLC_settings[$i]} ${MiB4_8_way_set[$i]}
done
firesim infrasetup
firesim runworkload
RESULT_NAME=$(ls $RESULT_DIR -t | head -1)
4MBLLC_8WAY_RESULT_DIR=${RESULT_DIR}/${RESULT_NAME}
firesim kill

# Run sweep w/ 4 MiB 4-way LLC
for i in ${!LLC_settings[@]}; do
    python3 $CHANGE_CONF_PY fased-sweep-protomegaboom.conf ${LLC_settings[$i]} ${MiB4_4_way_set[$i]}
done
firesim infrasetup
firesim runworkload
RESULT_NAME=$(ls $RESULT_DIR -t | head -1)
4MBLLC_4WAY_RESULT_DIR=${RESULT_DIR}/${RESULT_NAME}
firesim kill

# Run sweep w/ 4 MiB 2-way LLC
for i in ${!LLC_settings[@]}; do
    python3 $CHANGE_CONF_PY fased-sweep-protomegaboom.conf ${LLC_settings[$i]} ${MiB4_2_way_set[$i]}
done
firesim infrasetup
firesim runworkload
RESULT_NAME=$(ls $RESULT_DIR -t | head -1)
4MBLLC_2WAY_RESULT_DIR=${RESULT_DIR}/${RESULT_NAME}
firesim kill

# Run sweep w/ 4 MiB direct mapped LLC
for i in ${!LLC_settings[@]}; do
    python3 $CHANGE_CONF_PY fased-sweep-protomegaboom.conf ${LLC_settings[$i]} ${MiB4_direct_mapped[$i]}
done
firesim infrasetup
firesim runworkload
RESULT_NAME=$(ls $RESULT_DIR -t | head -1)
4MBLLC_DMAP_RESULT_DIR=${RESULT_DIR}/${RESULT_NAME}
firesim kill

# Run sweep w/ 32 MiB direct mapped LLC
for i in ${!LLC_settings[@]}; do
    python3 $CHANGE_CONF_PY fased-sweep-protomegaboom.conf ${LLC_settings[$i]} ${MiB32_direct_mapped[$i]}
done
firesim infrasetup
firesim runworkload
RESULT_NAME=$(ls $RESULT_DIR -t | head -1)
32MBLLC_DMAP_RESULT_DIR=${RESULT_DIR}/${RESULT_NAME}
firesim terminaterunfarm --forceterminate
