#!/usr/bin/bash

# Runs a given workload on multiple different LLC cache configurations to obtain 
# FASED performance results
#
# Arguments
#     arg1: workload name
#     arg2: job name
#
# Supported workload : jobs
#     caches-br  : caches
#     strided-br : strided
#
# Example Usage
#     ./run-cache-sweep caches-br caches
HOME_DIR=/home/centos/firesim
RESULT_DIR=${HOME_DIR}/deploy/results-workload
WORK_DIR=${HOME_DIR}/deploy/workloads/ccbench-new
COPY_DIR=${WORK_DIR}/results
FIRESIM_CONFIGS=${WORK_DIR}/software/firesim-configs
WORKLOAD=${1}
JOB=${2}
RUNTIME_CONFIG_LLC=FASED_LLC_${WORKLOAD}_sweep_runtime.ini
RUNTIME_CONFIG_NO_LLC=FASED_no_LLC_${WORKLOAD}_sweep_runtime.ini
LLC_settings=(
    "mm_llc_wayBits_0"
    "mm_llc_setBits_0"
    "mm_llc_blockBits_0"
    "mm_llc_activeMSHRs_0"
    "mm_llc_wayBits_1"
    "mm_llc_setBits_1"
    "mm_llc_blockBits_1"
    "mm_llc_activeMSHRs_1"
    "mm_llc_wayBits_2"
    "mm_llc_setBits_2"
    "mm_llc_blockBits_2"
    "mm_llc_activeMSHRs_2"
    "mm_llc_wayBits_3"
    "mm_llc_setBits_3"
    "mm_llc_blockBits_3"
    "mm_llc_activeMSHRs_3"
)
MiB4_8_way_set=(3 10 7 8 3 10 7 8 3 10 7 8 3 10 7 8)
MiB4_4_way_set=(2 11 7 8 2 11 7 8 2 11 7 8 2 11 7 8)
MiB4_2_way_set=(1 12 7 8 1 12 7 8 1 12 7 8 1 12 7 8)
MiB4_direct_mapped=(0 13 7 8 0 13 7 8 0 13 7 8 0 13 7 8)
MiB32_direct_mapped=(0 16 7 8 0 16 7 8 0 16 7 8 0 16 7 8)

cd $WORK_DIR

# Clear copy directory if it is not empty
if [ ! -z "$(ls -A $COPY_DIR)" ]; then
    rm -r ${COPY_DIR}/*
fi

# Initialize separate directories for each different configuration
mkdir ${COPY_DIR}/no_LLC
mkdir ${COPY_DIR}/MiB4_8_way_set
mkdir ${COPY_DIR}/MiB4_4_way_set
mkdir ${COPY_DIR}/MiB4_2_way_set
mkdir ${COPY_DIR}/MiB4_direct_mapped
mkdir ${COPY_DIR}/MiB32_direct_mapped


# Configuring config_runtime.ini for the no-LLC sim
cp ${FIRESIM_CONFIGS}/${RUNTIME_CONFIG_NO_LLC} ${HOME_DIR}/deploy/config_runtime.ini

# Run sweep with no-LLC configuration
firesim launchrunfarm
firesim infrasetup
firesim runworkload
firesim terminaterunfarm

RESULT_NAME=$(ls $RESULT_DIR -t | head -1)
cp ${RESULT_DIR}/${RESULT_NAME}/${WORKLOAD}-${JOB}/run_result.csv ${COPY_DIR}/no_LLC/run_result.csv
cp ${RESULT_DIR}/${RESULT_NAME}/${WORKLOAD}-${JOB}/uartlog ${COPY_DIR}/no_LLC/uartlog


# Configuring config_runtime.ini for the LLC sims
cp ${FIRESIM_CONFIGS}/${RUNTIME_CONFIG_LLC} ${HOME_DIR}/deploy/config_runtime.ini
firesim launchrunfarm

# Run sweep with 4 MiB 8-way
for i in ${!LLC_settings[@]}; do
    python3 change-conf.py fased_sweep_protomegaboom.conf ${LLC_settings[$i]} ${MiB4_8_way_set[$i]}
done
firesim infrasetup
firesim runworkload

RESULT_NAME=$(ls $RESULT_DIR -t | head -1)
cp ${RESULT_DIR}/${RESULT_NAME}/${WORKLOAD}-${JOB}/run_result.csv ${COPY_DIR}/MiB4_8_way_set/run_result.csv
cp ${RESULT_DIR}/${RESULT_NAME}/${WORKLOAD}-${JOB}/uartlog ${COPY_DIR}/MiB4_8_way_set/uartlog

# Run sweep with 4 MiB 4-way
firesim kill

for i in ${!LLC_settings[@]}; do
    python3 change-conf.py fased_sweep_protomegaboom.conf ${LLC_settings[$i]} ${MiB4_4_way_set[$i]}
done
firesim infrasetup
firesim runworkload

RESULT_NAME=$(ls $RESULT_DIR -t | head -1)
cp ${RESULT_DIR}/${RESULT_NAME}/${WORKLOAD}-${JOB}/run_result.csv ${COPY_DIR}/MiB4_4_way_set/run_result.csv
cp ${RESULT_DIR}/${RESULT_NAME}/${WORKLOAD}-${JOB}/uartlog ${COPY_DIR}/MiB4_4_way_set/uartlog

# Run sweep with 4 MiB 2-way
firesim kill

for i in ${!LLC_settings[@]}; do
    python3 change-conf.py fased_sweep_protomegaboom.conf ${LLC_settings[$i]} ${MiB4_2_way_set[$i]}
done
firesim infrasetup
firesim runworkload

RESULT_NAME=$(ls $RESULT_DIR -t | head -1)
cp ${RESULT_DIR}/${RESULT_NAME}/${WORKLOAD}-${JOB}/run_result.csv ${COPY_DIR}/MiB4_2_way_set/run_result.csv
cp ${RESULT_DIR}/${RESULT_NAME}/${WORKLOAD}-${JOB}/uartlog ${COPY_DIR}/MiB4_2_way_set/uartlog

# Run sweep with 4 MiB direct mapped
firesim kill

for i in ${!LLC_settings[@]}; do
    python3 change-conf.py fased_sweep_protomegaboom.conf ${LLC_settings[$i]} ${MiB4_direct_mapped[$i]}
done
firesim infrasetup
firesim runworkload

RESULT_NAME=$(ls $RESULT_DIR -t | head -1)
cp ${RESULT_DIR}/${RESULT_NAME}/${WORKLOAD}-${JOB}/run_result.csv ${COPY_DIR}/MiB4_direct_mapped/run_result.csv
cp ${RESULT_DIR}/${RESULT_NAME}/${WORKLOAD}-${JOB}/uartlog ${COPY_DIR}/MiB4_direct_mapped/uartlog

# Run sweep with 32 MiB direct mapped
firesim kill

for i in ${!LLC_settings[@]}; do
    python3 change-conf.py fased_sweep_protomegaboom.conf ${LLC_settings[$i]} ${MiB32_direct_mapped[$i]}
done
firesim infrasetup
firesim runworkload

RESULT_NAME=$(ls $RESULT_DIR -t | head -1)
cp ${RESULT_DIR}/${RESULT_NAME}/${WORKLOAD}-${JOB}/run_result.csv ${COPY_DIR}/MiB32_direct_mapped/run_result.csv
cp ${RESULT_DIR}/${RESULT_NAME}/${WORKLOAD}-${JOB}/uartlog ${COPY_DIR}/MiB32_direct_mapped/uartlog

# Simulations done
firesim terminaterunfarm
